---
   - name: install tomcat8
     yum: name=tomcat8 state=present update_cache=yes
     when: ansible_distribution == 'Amazon'
     
   - name: service start
     service: name=tomcat8 state=started
     when: ansible_distribution == 'Amazon'
  
