---
   - name: install tomcat8
     apt: name=tomcat8 state=present update_cache=yes
     when: ansible_distribution == 'Ubuntu'
     
   - name: service start
     service: name=tomcat8 state=started
     when: ansible_distribution == 'Ubuntu'

