---
  - name: install nginx
    yum: name=nginx state=present update_cache=yes
    when: ansible_distribution == 'Amazon'

  - name: start the service
    service: name=nginx state=started
    when: ansible_distribution == 'Amazon'
 
