---
  - name: add repo
    apt_repository: repo=ppa:webupd8team/java state=present
    when: ansible_distribution == 'Ubuntu'

  - name: download package
    apt: name=oracle-java8-installer state=present update_cache=yes
    when: ansible_distribution == 'Ubuntu'

  - name: set java home
    lineinfile: 
        path: /etc/environment
        line: JAVA_HOME="/usr/lib/jvm/java-8-oracle"
        create: yes
    when: ansible_distribution == 'Ubuntu'
  
